name: Rust

on: [push, pull_request]

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Server
      run: cargo build --verbose
  
  build-terminal-chat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terminal-chat
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Terminal Chat
      run: cargo build --verbose
